# Generated by Django 5.2.8 on 2026-02-12 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, help_text="User's affiliated institution", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='notes.institution'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization_courses',
            field=models.ManyToManyField(blank=True, help_text='Courses this moderator specializes in', related_name='specialized_moderators', to='notes.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization_subjects',
            field=models.ManyToManyField(blank=True, help_text='Specific subjects within courses', related_name='specialized_moderators', to='notes.subject'),
        ),
    ]
