# Generated by Django 5.2.8 on 2026-02-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_institution_user_specialization_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qualification_document',
            field=models.FileField(blank=True, help_text='Upload degree certificate, transcript, or other proof of qualification (PDF, JPG, PNG)', null=True, upload_to='qualifications/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification_notes',
            field=models.TextField(blank=True, help_text='Admin notes about qualification verification'),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification_verified',
            field=models.BooleanField(default=False, help_text='Admin has verified the qualification documents'),
        ),
    ]
