# Generated by Django 5.2.8 on 2026-03-15 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='is_download',
            field=models.BooleanField(default=True, help_text='False if just viewed, True if downloaded'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['user', '-downloaded_at'], name='notes_downl_user_id_4f4bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['note', '-downloaded_at'], name='notes_downl_note_id_3cd823_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['note', '-created_at'], name='notes_ratin_note_id_9879f9_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user'], name='notes_ratin_user_id_3332e4_idx'),
        ),
    ]
