# Generated by Django 5.2.8 on 2026-02-13 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('normal', 'Normal Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20)),
                ('report_count', models.IntegerField(default=0)),
                ('days_pending', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'moderator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_queue_items', to=settings.AUTH_USER_MODEL)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='notes.note')),
            ],
            options={
                'verbose_name': 'Moderation Queue Entry',
                'verbose_name_plural': 'Moderation Queue',
                'ordering': ['-priority', '-report_count', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve_trusted_users', models.BooleanField(default=False, help_text='Auto-approve notes from verified users with good history')),
                ('trusted_user_threshold', models.IntegerField(default=10, help_text='Number of approved notes needed to become trusted')),
                ('max_pending_days', models.IntegerField(default=7, help_text='Maximum days a note should be pending before escalation')),
                ('enable_auto_assignment', models.BooleanField(default=True, help_text='Automatically assign notes to moderators based on specialization')),
                ('load_balancing_enabled', models.BooleanField(default=True, help_text='Distribute notes evenly among moderators')),
                ('notify_on_assignment', models.BooleanField(default=True, help_text='Email moderators when notes are assigned')),
                ('notify_on_report', models.BooleanField(default=True, help_text='Email moderators when reports are filed')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation Settings',
                'verbose_name_plural': 'Moderation Settings',
            },
        ),
        migrations.CreateModel(
            name='ModeratorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Internal note visible only to moderators')),
                ('is_flagged', models.BooleanField(default=False, help_text='Flag for admin attention')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderator', models.ForeignKey(limit_choices_to={'role__in': ['moderator', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_notes', to='notes.note')),
            ],
            options={
                'verbose_name': 'Moderator Note',
                'verbose_name_plural': 'Moderator Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModeratorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_actions', models.IntegerField(default=0)),
                ('total_approvals', models.IntegerField(default=0)),
                ('total_rejections', models.IntegerField(default=0)),
                ('total_removals', models.IntegerField(default=0)),
                ('avg_processing_time', models.FloatField(default=0.0, help_text='Average time to process a note (in minutes)')),
                ('accuracy_score', models.FloatField(default=0.0, help_text='Accuracy score based on admin reviews (0-100)')),
                ('last_action_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderator', models.OneToOneField(limit_choices_to={'role': 'moderator'}, on_delete=django.db.models.deletion.CASCADE, related_name='performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderator Performance',
                'verbose_name_plural': 'Moderator Performances',
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('approve', 'Approved Content'), ('reject', 'Rejected Content'), ('remove', 'Removed Content'), ('warn', 'Warned User'), ('restore', 'Restored Content'), ('edit', 'Edited Content')], db_index=True, max_length=20)),
                ('reason', models.TextField(help_text='Reason for this moderation action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of moderator', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('moderator', models.ForeignKey(help_text='Moderator who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='notes.note')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='notes.report')),
                ('target_user', models.ForeignKey(blank=True, help_text='User who received this moderation action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation Action',
                'verbose_name_plural': 'Moderation Actions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['moderator', '-created_at'], name='moderation__moderat_59647a_idx'), models.Index(fields=['action_type', '-created_at'], name='moderation__action__989271_idx'), models.Index(fields=['note', '-created_at'], name='moderation__note_id_13403a_idx')],
            },
        ),
    ]
